stages:
  - build
  - push

variables:
  DOCKER_DRIVER: overlay2
  REGISTRY: git.fhict.nl/I506400/my-individual-assignment-semester-3_fe
  IMAGE_TAG: $CI_COMMIT_SHA

build:
  stage: build
  script: 
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist/

push:
  stage: push
  script:
    - |
      if [[ "$CI_COMMIT_REF_NAME" == "$CI_DEFAULT_BRANCH" ]]; then
        docker build -t $REGISTRY/frontend:$IMAGE_TAG .
        docker push $REGISTRY/frontend:$IMAGE_TAG
      else
        echo "Skipping Docker image build as the pipeline was not triggered from the main branch."
      fi
  only:
    - master
    - main
    - dev

