stages:
  - build
  - push

variables:
  DOCKER_DRIVER: overlay2
  REGISTRY: git.fhict.nl/i506400/my-individual-assignment-semester-3_fe
  IMAGE_TAG: $CI_COMMIT_SHA

build:
  stage: build
  script: 
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist/

push:
  stage: push
  script:
    - |
      if [[ "$CI_COMMIT_REF_NAME" == "$CI_DEFAULT_BRANCH" ]]; then
<<<<<<< HEAD
        docker build -t $REGISTRY/frontend:$IMAGE_TAG .
        docker push $REGISTRY/frontend:$IMAGE_TAG
=======
        lower_registry=$(echo $REGISTRY | tr '[:upper:]' '[:lower:]')
        docker build -t $lower_registry/frontend:$IMAGE_TAG .
        docker push $lower_registry/frontend:$IMAGE_TAG
>>>>>>> 5f9a471c23b9eb2aa3b2e2a664023f8afdf2f42b
      else
        echo "Skipping Docker image build as the pipeline was not triggered from the main branch."
      fi
  only:
    - master
    - main
    - dev
<<<<<<< HEAD
=======


>>>>>>> 5f9a471c23b9eb2aa3b2e2a664023f8afdf2f42b
